capabilities:
  streaming: True
defaultInputModes:
  - text
defaultOutputModes:
  - text
description: Report Agent
name: Report Agent
skills:
  - description: Analyze financial earnings Report
    examples:
      - Summarize the earnings report from Q2
    name: Returns Report Agent
    tags:
      - report_agent
supportsAuthenticatedExtendedCard: false
url: "http://0.0.0.0:8000"
version: 1.0.0
