opening_text: |
  Hi, how can I assist you today?

greeting_questions:
  - Summarize the earnings from last quarter
  - What are the key takeaway from the last earnings call?

no_data_found: "No data found"

fallback_response: "I didn't understand your question. Kindly rephrase it!"
